"""Supported CLI definitions (Claude, Codex, Gemini, Antigravity, DeepSeek)."""

CLI_SPECS = {
    "claude": {
        "label": "Claude",
        "commands": ["claude"],
        "install": "npm install -g @anthropic-ai/claude-code",
        "install_alt": "claude install stable",
        "auth_help": "Click Log in (opens terminal with claude setup-token), paste the generated token below, and Save.",
        "login_args": ["setup-token"],
        "token_env": "CLAUDE_CODE_OAUTH_TOKEN",
        "token_hint": "Paste the sk-ant-oat01-... token generated by claude setup-token",
        "version_args": ["--version"],
        "ping_prompt": "HI",
    },
    "gpt": {
        "label": "ChatGPT (Codex)",
        "commands": ["codex"],
        "install": "npm install -g @openai/codex",
        "auth_help": "Click Log in (opens terminal with codex login) or run it in your shell.",
        "login_args": ["login"],
        "version_args": ["--version"],
        "ping_prompt": "HI",
    },
    "gemini": {
        "label": "Gemini",
        "commands": ["gemini"],
        "install": "npm install -g @google/gemini-cli",
        "auth_help": "Individual/free-tier OAuth for Gemini CLI was discontinued. Use enterprise/API key or the Antigravity CLI card.",
        "login_args": [],
        "version_args": ["--version"],
        "ping_prompt": "HI",
    },
    "antigravity": {
        "label": "Antigravity CLI",
        "commands": ["agy"],
        "install": "curl -fsSL https://antigravity.google/cli/install.sh | bash",
        "install_windows": "powershell -NoProfile -ExecutionPolicy Bypass -Command \"irm https://antigravity.google/cli/install.ps1 | iex\"",
        "auth_help": "Log in (opens agy), copy the generated key, paste below, and Save. Interactive login does not work in -p mode.",
        "login_args": [],
        "token_env": ["ANTIGRAVITY_API_KEY", "GEMINI_API_KEY"],
        "token_hint": "Paste the key generated by agy after login",
        "version_args": ["--version"],
        "ping_prompt": "HI",
    },
    "deepseek": {
        "label": "DeepSeek",
        "commands": ["deepseek", "deepseek-tui"],
        "install": "npm install -g deepseek-tui",
        "auth_help": "Click Log in (opens deepseek interactively) or set DEEPSEEK_API_KEY.",
        "login_args": [],
        "version_args": ["--version"],
        "ping_prompt": "HI",
    },
}

PKEY_ORDER = ["claude", "gpt", "gemini", "antigravity", "deepseek"]
